"""registration

Revision ID: 46942e480f26
Revises: 9c72dab52d08
Create Date: 2022-12-23 16:37:19.869935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46942e480f26'
down_revision = '9c72dab52d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('registration_link')

    # ### end Alembic commands ###
