"""added event dates

Revision ID: 99742c8bcddd
Revises: aa7edeac050d
Create Date: 2022-11-20 12:19:43.694196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99742c8bcddd'
down_revision = 'aa7edeac050d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
