"""update

Revision ID: bd34dc68f51d
Revises: 99742c8bcddd
Create Date: 2022-12-23 15:20:00.088339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd34dc68f51d'
down_revision = '99742c8bcddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('to_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('to_time')
        batch_op.drop_column('from_time')

    # ### end Alembic commands ###
